### ISSUE TITLE
03/17 #Team 94

### ISSUE THREAD

**Issue by Jmagero** [SevlaMare/CSS-course-platform#2]

**Comment by idgm5** [comment]
Just a small observation for the backgrounds in the illustrations inside your about page:
![image](https://i.imgur.com/HmjNd4F.png)

You can add a span tag and make it a block then give it a black background with some transparency, and for the position, you can use z-index property to make it stay behind the text but above the background image.

```
span {
  display: inline-block;
  position: absolute;
  z-index: 0;
  background: rgba(0, 0, 0, 0.5);
  width: 100%; 
  height: 40rem; 
}
```
I'm using height to give it some kind of size, you can adapt it to the framework you created. 

Cheers :)

**Comment by SevlaMare** [comment]
(For future reference)
Another approach is to use the image as a background:
background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.2)), url("images/team1.png");
or just adjust image direct.
